import pytest
from data360.model import (
    Asset,
    AssetClass,
    AssetType,
    BooleanFieldType,
    BooleanFieldTypeAttributes,
    ComputedOwnershipLookupFieldType,
    ComputedOwnershipLookupFieldTypeAttributes,
    ComputedRelationshipFieldType,
    ComputedRelationshipFieldTypeAttributes,
    ComputedRelationshipLookupFieldType,
    ComputedRelationshipLookupFieldTypeAttributes,
    ComputedRelationshipReferenceListFieldType,
    ComputedRelationshipReferenceListFieldTypeAttributes,
    CounterFieldType,
    CounterFieldTypeAttributes,
    DateFieldType,
    DateFieldTypeAttributes,
    DateTimeFieldType,
    DateTimeFieldTypeAttributes,
    DecimalFieldType,
    DecimalFieldTypeAttributes,
    DefinitionFieldType,
    Description,
    HtmlFieldType,
    HtmlFieldTypeAttributes,
    JsonElementFieldType,
    JsonElementFieldTypeAttributes,
    JsonFieldType,
    JsonFieldTypeAttributes,
    LinkFieldType,
    LinkFieldTypeAttributes,
    LookupFieldType,
    LookupFieldTypeAttributes,
    NumberFieldType,
    NumberFieldTypeAttributes,
    PathFieldType,
    PathFieldTypeAttributes,
    Predicate,
    PredicateType,
    ReferenceListFieldType,
    ReferenceListFieldTypeAttributes,
    Relationship,
    RelationshipFieldType,
    RelationshipFieldTypeAttributes,
    RelationshipType,
    ScoreFieldType,
    ScoreFieldTypeAttributes,
    SearchFieldType,
    SystemFieldType,
    SystemFieldTypeAttributes,
    TagFieldType,
    TagFieldTypeAttributes,
    TextFieldType,
    TextFieldTypeAttributes,
    Validation,
)
from tests.model_factory import (
    AssetClassFactory,
    AssetFactory,
    AssetTypeFactory,
    BooleanFieldTypeAttributesFactory,
    BooleanFieldTypeFactory,
    ComputedOwnershipLookupFieldTypeAttributesFactory,
    ComputedOwnershipLookupFieldTypeFactory,
    ComputedRelationshipFieldTypeAttributesFactory,
    ComputedRelationshipFieldTypeFactory,
    ComputedRelationshipLookupFieldTypeAttributesFactory,
    ComputedRelationshipLookupFieldTypeFactory,
    ComputedRelationshipReferenceListFieldTypeAttributesFactory,
    ComputedRelationshipReferencelistFieldTypeFactory,
    CounterFieldTypeAttributesFactory,
    CounterFieldTypeFactory,
    DateFieldTypeAttributesFactory,
    DateFieldTypeFactory,
    DateTimeFieldTypeAttributesFactory,
    DateTimeFieldTypeFactory,
    DecimalFieldTypeAttributesFactory,
    DecimalFieldTypeFactory,
    DefinitionFieldTypeFactory,
    DescriptionFactory,
    HtmlFieldTypeAttributesFactory,
    HtmlFieldTypeFactory,
    JsonElementFieldTypeAttributesFactory,
    JsonElementFieldTypeFactory,
    JsonFieldTypeAttributesFactory,
    JsonFieldTypeFactory,
    LinkFieldTypeAttributesFactory,
    LinkFieldTypeFactory,
    LookupFieldTypeAttributesFactory,
    LookupFieldTypeFactory,
    NumberFieldTypeAttributesFactory,
    NumberFieldTypeFactory,
    PathFieldTypeAttributesFactory,
    PathFieldTypeFactory,
    PredicateFactory,
    PredicateTypeFactory,
    ReferenceListFieldTypeAttributesFactory,
    ReferenceListFieldTypeFactory,
    RelationshipFactory,
    RelationshipFieldTypeAttributesFactory,
    RelationshipFieldTypeFactory,
    RelationshipTypeFactory,
    ScoreFieldTypeAttributesFactory,
    ScoreFieldTypeFactory,
    SearchFieldTypeFactory,
    SystemFieldTypeAttributesFactory,
    SystemFieldTypeFactory,
    TagFieldTypeAttributesFactory,
    TagFieldTypeFactory,
    TextFieldTypeAttributesFactory,
    TextFieldTypeFactory,
    ValidationFactory,
)


@pytest.mark.parametrize(
    "objectClass, factoryClass",
    [
        (AssetClass, AssetClassFactory),
        (AssetType, AssetTypeFactory),
        (Asset, AssetFactory),
        (PredicateType, PredicateTypeFactory),
        (Predicate, PredicateFactory),
        (RelationshipType, RelationshipTypeFactory),
        (Relationship, RelationshipFactory),
        (SearchFieldType, SearchFieldTypeFactory),
        (Description, DescriptionFactory),
        (Validation, ValidationFactory),
        (DefinitionFieldType, DefinitionFieldTypeFactory),
        (BooleanFieldTypeAttributes, BooleanFieldTypeAttributesFactory),
        (BooleanFieldType, BooleanFieldTypeFactory),
        (
            ComputedOwnershipLookupFieldTypeAttributes,
            ComputedOwnershipLookupFieldTypeAttributesFactory,
        ),
        (ComputedOwnershipLookupFieldType, ComputedOwnershipLookupFieldTypeFactory),
        (
            ComputedRelationshipFieldTypeAttributes,
            ComputedRelationshipFieldTypeAttributesFactory,
        ),
        (ComputedRelationshipFieldType, ComputedRelationshipFieldTypeFactory),
        (
            ComputedRelationshipLookupFieldTypeAttributes,
            ComputedRelationshipLookupFieldTypeAttributesFactory,
        ),
        (
            ComputedRelationshipLookupFieldType,
            ComputedRelationshipLookupFieldTypeFactory,
        ),
        (
            ComputedRelationshipReferenceListFieldTypeAttributes,
            ComputedRelationshipReferenceListFieldTypeAttributesFactory,
        ),
        (
            ComputedRelationshipReferenceListFieldType,
            ComputedRelationshipReferencelistFieldTypeFactory,
        ),
        (ReferenceListFieldTypeAttributes, ReferenceListFieldTypeAttributesFactory),
        (ReferenceListFieldType, ReferenceListFieldTypeFactory),
        (CounterFieldTypeAttributes, CounterFieldTypeAttributesFactory),
        (CounterFieldType, CounterFieldTypeFactory),
        (DateFieldTypeAttributes, DateFieldTypeAttributesFactory),
        (DateFieldType, DateFieldTypeFactory),
        (DateTimeFieldTypeAttributes, DateTimeFieldTypeAttributesFactory),
        (DateTimeFieldType, DateTimeFieldTypeFactory),
        (DecimalFieldTypeAttributes, DecimalFieldTypeAttributesFactory),
        (DecimalFieldType, DecimalFieldTypeFactory),
        (HtmlFieldTypeAttributes, HtmlFieldTypeAttributesFactory),
        (HtmlFieldType, HtmlFieldTypeFactory),
        (JsonFieldTypeAttributes, JsonFieldTypeAttributesFactory),
        (JsonFieldType, JsonFieldTypeFactory),
        (JsonElementFieldTypeAttributes, JsonElementFieldTypeAttributesFactory),
        (JsonElementFieldType, JsonElementFieldTypeFactory),
        (LinkFieldTypeAttributes, LinkFieldTypeAttributesFactory),
        (LinkFieldType, LinkFieldTypeFactory),
        (LookupFieldTypeAttributes, LookupFieldTypeAttributesFactory),
        (LookupFieldType, LookupFieldTypeFactory),
        (NumberFieldTypeAttributes, NumberFieldTypeAttributesFactory),
        (NumberFieldType, NumberFieldTypeFactory),
        (PathFieldTypeAttributes, PathFieldTypeAttributesFactory),
        (PathFieldType, PathFieldTypeFactory),
        (RelationshipFieldTypeAttributes, RelationshipFieldTypeAttributesFactory),
        (RelationshipFieldType, RelationshipFieldTypeFactory),
        (TextFieldTypeAttributes, TextFieldTypeAttributesFactory),
        (TextFieldType, TextFieldTypeFactory),
        (TagFieldTypeAttributes, TagFieldTypeAttributesFactory),
        (TagFieldType, TagFieldTypeFactory),
        (ScoreFieldTypeAttributes, ScoreFieldTypeAttributesFactory),
        (ScoreFieldType, ScoreFieldTypeFactory),
        (SystemFieldTypeAttributes, SystemFieldTypeAttributesFactory),
        (SystemFieldType, SystemFieldTypeFactory),
    ],
)
def test_factory_builds_correct_object(objectClass, factoryClass):
    o = factoryClass.build()

    assert isinstance(o, objectClass)
